---
# vars file for tomcat
tomcat:
    appgroup: main
    appuser: main
    gid: 5000
    uid: 5000

    java:
        home: '/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.131-2.6.9.0.el7_3.x86_64/jre'
        opts: '
            -Duser.timezone=UTC
            -Dfile.encoding=UTF8
            -Xmx512m
            -Xms512m
            '
    catalina:
        home: '/usr/local/apache-tomcat-8.0.23/'
        pid:  '/usr/local/apache-tomcat-8.0.23/temp/tomcat.pid'
        opts: '-Dcom.sun.management.jmxremote
               -Dcom.sun.management.jmxremote.port=8082
               -Dcom.sun.management.jmxremote.authenticate=false
               -Dcom.sun.management.jmxremote.ssl=false'
